### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by manu-chroma** [SameerIITKGP/digitRecognition#1]
Hey,
I'm interested in trying out this code. Can you please update the README with the instructions to run the project.

**Comment by sameeriitkgp** [comment]
Yeah sure!
One thing,
The digitrecognition works with very good accuracy. But the thing is :
The code is not complete, I've tested it by hardcoding the co-ordinates of the digits.
So even if you use this, you would have to use some algorithm like contour detection to detect the digits and then use the functions provided.
I'm planning to develop this in the summers. But you are welcome, if you would like to.

**Comment by manu-chroma** [comment]
Ok thanks.
